from typing import Protocol

class SnapshotRepository(Protocol):
    async def save_snapshot(self, aggregate_id: str, aggregate_type: str,
        data: dict, version: int) -> None: ...
    async def load_snapshot(self, aggregate_id: str) -> dict | None: ...
    async def delete_snapshots(self, aggregate_id: str) -> None: ...
