[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
ignored_error_codes = [6275, 1878]
ffi = true
via_ir = true

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
ignored_error_codes = [6275, 1878]
ffi = true
via_ir = true
